ci(test-crates): install rudra with --locked
Otherwise:
error: failed to compile `rudra v0.1.0 (/home/runner/work/charon-rudra/charon-rudra/tests-crates/Rudra)`, intermediate artifacts can be found at `/home/runner/work/charon-rudra/charon-rudra/tests-crates/Rudra/target`

Caused by:
  package `libc v0.2.170` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.58.0-nightly